IsRebar3 = erlang:function_exported(rebar3, main, 1),

Rebar2Deps = [
    {lager, ".*", {git, "https://github.com/erlang-lager/lager.git", {tag, "3.8.0"}}},
    {jsone, ".*", {git, "https://github.com/sile/jsone.git", {tag, "1.5.2"}}},
    {esq, ".*", {git, "https://github.com/fogfish/esq.git", {tag, "2.0.4"}}}
],

case IsRebar3 of
    true ->
        CONFIG;
    false ->
        lists:keyreplace(deps, 1, CONFIG, {deps, Rebar2Deps})
end.
